// GENERATED FILE — do not edit by hand.
//
// Source: scripts/gs1_extended_attribute_master_code_list.csv
// Regenerate with: node scripts/build-gs1-code-lists.mjs
//
// 40 of 128 GS1 code lists (881 of 1987 values) — only those
// referenced by the demo categories. Values and codes are verbatim from the
// source apart from the ASCII normalizations the generator reports.

export interface Gs1Value {
  label: string
  code: string
}

/** Keyed by GS1 code list name, which is also the attribute label shown in the UI. */
export const GS1_CODE_LISTS: Record<string, Gs1Value[]> = {
  "Band Type": [
    { label: "Bangle", code: "JW03WBNDBA" },
    { label: "Bracelet", code: "JW03WBNDBR" },
    { label: "Cuff", code: "JW03WBNDCU" },
    { label: "NATO Strap", code: "JW03WBNDNA" },
    { label: "Strap", code: "JW03WBNDST" },
    { label: "Other", code: "JW04WBND99" },
  ],
  "Boot Shaft Type": [
    { label: "Knee High/Tall", code: "GM03BTSTKH" },
    { label: "Low Shaft", code: "GM03BTSTLS" },
    { label: "Low shaft/Ankle", code: "GM03BTSTAN" },
    { label: "Mid Calf", code: "GM03BTSTMI" },
    { label: "Over Knee XX", code: "GM03BTSTOK" },
    { label: "Tall", code: "GM03BTSTTL" },
    { label: "Other", code: "GMOBTST99" },
  ],
  "Bracelet Type": [
    { label: "Adjustable", code: "JW03BRTTAD" },
    { label: "Bangle", code: "JW03BRTTBA" },
    { label: "Bracelet Set", code: "JW03BRTTBS" },
    { label: "Chain", code: "JW03BRTTCH" },
    { label: "Charm", code: "JW03BRTTCM" },
    { label: "Coil", code: "JW03BRTTCL" },
    { label: "Cuff", code: "JW03BRTTCF" },
    { label: "Hinge", code: "JW03BRTTHN" },
    { label: "Line", code: "JW03BRTTLI" },
    { label: "Open Cuff", code: "JW03BRTTOC" },
    { label: "Stretch", code: "JW03BRTTST" },
    { label: "Wrap", code: "JW03BRTTWR" },
    { label: "Other", code: "JW04BRTT99" },
  ],
  "Care Instructions": [
    { label: "Dishwasher Safe", code: "GM03CAINDS" },
    { label: "Do Not Iron", code: "GM03CAINDN" },
    { label: "Dry Clean", code: "GM03CAINDC" },
    { label: "Hand Wash", code: "GM03CAINHW" },
    { label: "Leather Method Dry Cleaning", code: "GM03CAINLM" },
    { label: "Machine Wash Cold", code: "GM03CAINMC" },
    { label: "Machine Wash Dry Flat", code: "GM03CAINMD" },
    { label: "Machine Wash Hot", code: "GM03CAINMH" },
    { label: "Machine Wash Line Dry", code: "GM03CAINML" },
    { label: "Machine Wash Tumble Dry", code: "GM03CAINMT" },
    { label: "Machine Wash Warm", code: "GM03CAINMW" },
    { label: "Spot Clean", code: "GM03CAINSC" },
    { label: "Wash Separately", code: "GM03CAINWS" },
    { label: "Other", code: "GM04CAIN99" },
  ],
  "Closure": [
    { label: "1/2 Zip", code: "GM03CLOSZH" },
    { label: "1/4 Zip", code: "GM03CLOSZQ" },
    { label: "Adjustable/Pull", code: "GM03CLOSAP" },
    { label: "Back", code: "GM03CLOSBC" },
    { label: "Back Button/Zip", code: "GM03CLOSBB" },
    { label: "Back Hook/Zip", code: "GM03CLOSBH" },
    { label: "Barrel", code: "GM03CLOSBA" },
    { label: "Box Tab Insert", code: "GM03CLOSBT" },
    { label: "Buckle", code: "GM03CLOSBU" },
    { label: "Button", code: "GM03CLOSBN" },
    { label: "Button Back", code: "GM03CLOSBK" },
    { label: "Button Front", code: "GM03CLOSBF" },
    { label: "Button Front Partial", code: "GM03CLOSBP" },
    { label: "Button Shoulder", code: "GM03CLOSBS" },
    { label: "Clasp", code: "GM03CLOSCL" },
    { label: "Click Top", code: "GM03CLOSCT" },
    { label: "Clip On", code: "GM03CLOSCO" },
    { label: "D Ring", code: "GM03CLOSDR" },
    { label: "Drawstring", code: "GM03CLOSDS" },
    { label: "Drawstring Elastic", code: "GM03CLOSDE" },
    { label: "Drawstring Front", code: "GM03CLOSDF" },
    { label: "Elastic Lace with Toggle", code: "GM03CLOSET" },
    { label: "Fishhook", code: "GM03CLOSFS" },
    { label: "Flap", code: "GM03CLOSFP" },
    { label: "Foldover", code: "GM03CLOSFO" },
    { label: "French Wire", code: "GM03CLOSFW" },
    { label: "Frog/Button Loop", code: "GM03CLOSFA" },
    { label: "Front Button/Zip", code: "GM03CLOSFZ" },
    { label: "Front Hook/Zip", code: "GM03CLOSFH" },
    { label: "Hidden Button Front", code: "GM03CLOSHB" },
    { label: "Hidden Snap Front", code: "GM03CLOSHS" },
    { label: "Hidden Zip Front", code: "GM03CLOSHZ" },
    { label: "Hinged", code: "GM03CLOSHI" },
    { label: "Hinged/Foldover", code: "GM03CLOSHE" },
    { label: "Hook", code: "GM03CLOSHO" },
    { label: "Hook and Loop", code: "GM03CLOSHL" },
    { label: "Hook-and-eye", code: "GM03CLOSHC" },
    { label: "Hook-and-eye Back Front", code: "GM03CLOSHD" },
    { label: "Keyhole Button", code: "GM03CLOSKB" },
    { label: "Kiss-Lock", code: "GM03CLOSKL" },
    { label: "Knot", code: "GM03CLOSKN" },
    { label: "Lace Up", code: "GM03CLOSLU" },
    { label: "Lace-up Front", code: "GM03CLOSLF" },
    { label: "Latch", code: "GM03CLOSLA" },
    { label: "Leverback", code: "GM03CLOSLB" },
    { label: "Lift-Lock", code: "GM03CLOSLL" },
    { label: "Link/Clasp", code: "GM03CLOSLC" },
    { label: "Lobster Claw", code: "GM03CLOSLW" },
    { label: "Magnetic", code: "GM03CLOSMG" },
    { label: "O Ring", code: "GM03CLOSDO" },
    { label: "Pierced Post", code: "GM03CLOSPP" },
    { label: "Push-Lock", code: "GM03CLOSPL" },
    { label: "Side Button/Zip", code: "GM03CLOSSB" },
    { label: "Side Hook/Zip", code: "GM03CLOSSZ" },
    { label: "Snap", code: "GM03CLOSSN" },
    { label: "Snap Back", code: "GM03CLOSSM" },
    { label: "Snap Front", code: "GM03CLOSSF" },
    { label: "Snap Front Partial", code: "GM03CLOSS2" },
    { label: "Snap Legs", code: "GM03CLOSSE" },
    { label: "Snap Post", code: "GM03CLOSSA" },
    { label: "Snap Shoulder", code: "GM03CLOSSS" },
    { label: "String", code: "GM03CLOSSR" },
    { label: "Swivel", code: "GM03CLOSSW" },
    { label: "Tab", code: "GM03CLOSTB" },
    { label: "Tie", code: "GM03CLOSTI" },
    { label: "Tie Back/Halter", code: "GM03CLOSTH" },
    { label: "Tie Front", code: "GM03CLOSTF" },
    { label: "Tie Side", code: "GM03CLOSTS" },
    { label: "Toggle", code: "GM03CLOSTO" },
    { label: "Toggle Front", code: "GM03CLOSTN" },
    { label: "Top Zip", code: "GM03CLOSTZ" },
    { label: "Tunnel Side Tie", code: "GM03CLOSTQ" },
    { label: "Turn Lock", code: "GM03CLOSTL" },
    { label: "Wrap", code: "GM03CLOSWR" },
    { label: "Zipper", code: "GM03CLOSZI" },
    { label: "Zipper Around", code: "GM03CLOSZA" },
    { label: "Zipper Back", code: "GM03CLOSZB" },
    { label: "Zipper Back Partial", code: "GM03CLOSZP" },
    { label: "Zipper Front", code: "GM03CLOSZE" },
    { label: "Zipper Front Partial", code: "GM03CLOSZR" },
    { label: "Zipper Side", code: "GM03CLOSZS" },
    { label: "Other Closure", code: "GM04CLOS99" },
  ],
  "Collar/Neck Type": [
    { label: "1/4-Zip Mock", code: "GM03CLNTQZ" },
    { label: "Ballet", code: "GM03CLNTBL" },
    { label: "Banded", code: "GM03CLNTBC" },
    { label: "Boat or Bateau", code: "GM03CLNTBE" },
    { label: "Button-Down", code: "GM03CLNTBD" },
    { label: "Cowl", code: "GM03CLNTCW" },
    { label: "Crew", code: "GM03CLNTCR" },
    { label: "Drape", code: "GM03CLNTDP" },
    { label: "Funnel", code: "GM03CLNTFU" },
    { label: "Halter", code: "GM03CLNTHA" },
    { label: "Henley", code: "GM03CLNTHN" },
    { label: "Henley Faux", code: "GM03CLNTHF" },
    { label: "Henley Functional", code: "GM03CLNTHU" },
    { label: "Jewel", code: "GM03CLNTJE" },
    { label: "Johnny", code: "GM03CLNTJO" },
    { label: "Keyhole", code: "GM03CLNTKE" },
    { label: "Mandarin", code: "GM03CLNTMB" },
    { label: "Marilyn", code: "GM03CLNTMI" },
    { label: "Mockneck", code: "GM03CLNTMO" },
    { label: "Necklace", code: "GM03CLNTNE" },
    { label: "Notch", code: "GM03CLNTNO" },
    { label: "Off the Shoulder", code: "GM03CLNTOR" },
    { label: "One Shoulder", code: "GM03CLNTOS" },
    { label: "Ottoman", code: "GM03CLNTOT" },
    { label: "Peter Pan", code: "GM03CLNTPA" },
    { label: "Platter", code: "GM03CLNTPE" },
    { label: "Plunge", code: "GM03CLNTPJ" },
    { label: "Point", code: "GM03CLNTPO" },
    { label: "Polo", code: "GM03CLNTPU" },
    { label: "Portrait Collar", code: "GM03CLNTPR" },
    { label: "Racer Back", code: "GM03CLNTRB" },
    { label: "Rolled", code: "GM03CLNTRO" },
    { label: "Round", code: "GM03CLNTRU" },
    { label: "Sailor", code: "GM03CLNTSD" },
    { label: "Scoop", code: "GM03CLNTSC" },
    { label: "Shawl", code: "GM03CLNTSH" },
    { label: "Slider Halter", code: "GM03CLNTSL" },
    { label: "Spread", code: "GM03CLNTSO" },
    { label: "Square", code: "GM03CLNTSQ" },
    { label: "Stand", code: "GM03CLNTSV" },
    { label: "Surplice", code: "GM03CLNTSU" },
    { label: "Sweetheart", code: "GM03CLNTSX" },
    { label: "Tab", code: "GM03CLNTTA" },
    { label: "Tie", code: "GM03CLNTTI" },
    { label: "Turtle", code: "GM03CLNTTU" },
    { label: "V-Neck", code: "GM03CLNTVN" },
    { label: "Wing", code: "GM03CLNTWI" },
    { label: "Y-Neck", code: "GM03CLNTYN" },
    { label: "Other Collar", code: "GM04CLNT99" },
  ],
  "Crown": [
    { label: "", code: "GM03CRWNNN" },
    { label: "High", code: "GM03CRWNHI" },
    { label: "Low", code: "GM03CRWNLW" },
    { label: "Mid", code: "GM03CRWNMD" },
    { label: "Other", code: "GM04CRWN99" },
  ],
  "Earring Type": [
    { label: "Button", code: "JW03EATPBU" },
    { label: "Chandelier", code: "JW03EATPCH" },
    { label: "Drop", code: "JW03EATPDR" },
    { label: "Ear Cuff", code: "JW03EATPEC" },
    { label: "Ear Jacket", code: "JW03EATPEJ" },
    { label: "Ear Wrap", code: "JW03EATPEW" },
    { label: "Hoop", code: "JW03EATPHP" },
    { label: "Stud", code: "JW03EATPST" },
    { label: "Other", code: "JW04EATP99" },
  ],
  "Fabric or Material": [
    { label: "14K Gold", code: "GM03FBMC14" },
    { label: "18K Gold", code: "GM03FBMC18" },
    { label: "Agate", code: "GM03FBMCAG" },
    { label: "Aluminum", code: "GM03FBMCAL" },
    { label: "Amethyst", code: "GM03FBMCAM" },
    { label: "Anodized Aluminum", code: "GM03FBMCAN" },
    { label: "Beaded", code: "GM03FBMCBD" },
    { label: "Bi-stretch", code: "GM03FBMCBF" },
    { label: "Birthstone", code: "GM03FBMCBE" },
    { label: "Bone", code: "GM03FBMCBG" },
    { label: "Boucle", code: "GM03FBMCBH" },
    { label: "Brass", code: "GM03FBMCBI" },
    { label: "Broadcloth", code: "GM03FBMCBJ" },
    { label: "Brocade", code: "GM03FBMCBL" },
    { label: "Bronze", code: "GM03FBMCBN" },
    { label: "Brushed Back Satin", code: "GM03FBMCBS" },
    { label: "Brushed Back Terry", code: "GM03FBMCBT" },
    { label: "Burlap", code: "GM03FBMCBU" },
    { label: "Canvas", code: "GM03FBMCCA" },
    { label: "Cashmink", code: "GM03FBMCCB" },
    { label: "Cast Aluminum", code: "GM03FBMCCC" },
    { label: "Cast Iron", code: "GM03FBMCCD" },
    { label: "Ceramic", code: "GM03FBMCCE" },
    { label: "Challis", code: "GM03FBMCCF" },
    { label: "Chambray", code: "GM03FBMCCG" },
    { label: "Charmeuse", code: "GM03FBMCCH" },
    { label: "Chenille", code: "GM03FBMCCI" },
    { label: "Chiffon/Sheer", code: "GM03FBMCCJ" },
    { label: "Coated Canvas", code: "GM03FBMCCK" },
    { label: "Composite", code: "GM03FBMCCL" },
    { label: "Confetti", code: "GM03FBMCCM" },
    { label: "Copper", code: "GM03FBMCCN" },
    { label: "Coral", code: "GM03FBMCCO" },
    { label: "Corduroy", code: "GM03FBMCCP" },
    { label: "Corian", code: "GM03FBMCCQ" },
    { label: "Cork", code: "GM03FBMCCR" },
    { label: "Crepe", code: "GM03FBMCCS" },
    { label: "Crinoline", code: "GM03FBMCCT" },
    { label: "Crochet", code: "GM03FBMCCU" },
    { label: "Crochet/Openwork", code: "GM03FBMCCV" },
    { label: "Croco", code: "GM03FBMCCW" },
    { label: "Croco Embossed", code: "GM03FBMCCX" },
    { label: "Crystal", code: "GM03FBMCCY" },
    { label: "Cubic Zirconia", code: "GM03FBMCCZ" },
    { label: "Denim", code: "GM03FBMCDA" },
    { label: "Diamond", code: "GM03FBMCDB" },
    { label: "Dobby", code: "GM03FBMCDC" },
    { label: "Double Knit", code: "GM03FBMCDD" },
    { label: "Down", code: "GM03FBMCDE" },
    { label: "Down Fill", code: "GM03FBMCDF" },
    { label: "Drop Needle", code: "GM03FBMCDG" },
    { label: "Earthenware", code: "GM03FBMCEA" },
    { label: "Elephant Embossed", code: "GM03FBMCEB" },
    { label: "Enamel", code: "GM03FBMCEC" },
    { label: "Enamel/Aluminum", code: "GM03FBMCED" },
    { label: "Enamel/Epoxy", code: "GM03FBMCEF" },
    { label: "Enamel/Iron", code: "GM03FBMCEG" },
    { label: "Enamel/Steel", code: "GM03FBMCEH" },
    { label: "End-on-End", code: "GM03FBMCEI" },
    { label: "Epoxy", code: "GM03FBMCEJ" },
    { label: "Eyelet", code: "GM03FBMCEK" },
    { label: "Fabric", code: "GM03FBMCFA" },
    { label: "Faux Fur", code: "GM03FBMCFB" },
    { label: "Faux Leather", code: "GM03FBMCFC" },
    { label: "Faux Pearl", code: "GM03FBMCFD" },
    { label: "Faux Shearling", code: "GM03FBMCFE" },
    { label: "Faux Suede", code: "GM03FBMCFF" },
    { label: "Felt", code: "GM03FBMCFG" },
    { label: "Flannel", code: "GM03FBMCFH" },
    { label: "Flat Knit", code: "GM03FBMCFI" },
    { label: "Fleece", code: "GM03FBMCFJ" },
    { label: "Foam", code: "GM03FBMCFK" },
    { label: "French Terry", code: "GM03FBMCFL" },
    { label: "Fresh Water Pearl", code: "GM03FBMCFM" },
    { label: "Fur", code: "GM03FBMCFN" },
    { label: "Gabardine", code: "GM03FBMCGA" },
    { label: "Galvanized", code: "GM03FBMCGB" },
    { label: "Gauze", code: "GM03FBMCGC" },
    { label: "Genuine Stone", code: "GM03FBMCGD" },
    { label: "Georgette", code: "GM03FBMCGE" },
    { label: "Glass", code: "GM03FBMCGF" },
    { label: "Glitter", code: "GM03FBMCGI" },
    { label: "Grenadine", code: "GM03FBMCGG" },
    { label: "Grosgrain", code: "GM03FBMCGH" },
    { label: "Hard Anodized", code: "GM03FBMCHA" },
    { label: "Hatchi", code: "GM03FBMCHB" },
    { label: "Heavy Gauge Steel", code: "GM03FBMCHC" },
    { label: "High-Carbon Steel", code: "GM03FBMCHD" },
    { label: "Hopsack", code: "GM03FBMCHE" },
    { label: "Howlite", code: "GM03FBMCHF" },
    { label: "Ironstone", code: "GM03FBMCIA" },
    { label: "Jacquard", code: "GM03FBMCJA" },
    { label: "Jade", code: "GM03FBMCJB" },
    { label: "Jasper", code: "GM03FBMCJC" },
    { label: "Knit (Generic)", code: "GM03FBMCKA" },
    { label: "Knit Cable", code: "GM03FBMCKB" },
    { label: "Knit Fine Gauge", code: "GM03FBMCKC" },
    { label: "Knit Intarsia", code: "GM03FBMCKD" },
    { label: "Knit Interlock", code: "GM03FBMCKE" },
    { label: "Knit Jersey", code: "GM03FBMCKF" },
    { label: "Knit Ribbed", code: "GM03FBMCKG" },
    { label: "Knit/Woven", code: "GM03FBMCKH" },
    { label: "Knitted", code: "GM03FBMCKI" },
    { label: "Lace", code: "GM03FBMCLA" },
    { label: "Leather", code: "GM03FBMCLB" },
    { label: "Lizard Embossed", code: "GM03FBMCLC" },
    { label: "Magnesite", code: "GM03FBMCMA" },
    { label: "Magnet", code: "GM03FBMCMB" },
    { label: "Marble", code: "GM03FBMCMC" },
    { label: "Marble/Wood", code: "GM03FBMCMD" },
    { label: "Matte Jersey", code: "GM03FBMCME" },
    { label: "Melamine", code: "GM03FBMCMF" },
    { label: "Mercury Glass", code: "GM03FBMCMG" },
    { label: "Mesh", code: "GM03FBMCMH" },
    { label: "Metal", code: "GM03FBMCMI" },
    { label: "Metal Alloy", code: "GM03FBMCMJ" },
    { label: "Metallic", code: "GM03FBMCMK" },
    { label: "Microfiber", code: "GM03FBMCML" },
    { label: "Microfleece", code: "GM03FBMCMM" },
    { label: "Mikado", code: "GM03FBMCMN" },
    { label: "Mixed Materials", code: "GM03FBMCMO" },
    { label: "Mogador", code: "GM03FBMCMP" },
    { label: "Moleskin", code: "GM03FBMCMQ" },
    { label: "Mother-of-Pearl", code: "GM03FBMCMR" },
    { label: "Natural", code: "GM03FBMCNA" },
    { label: "Natural Fiber", code: "GM03FBMCNB" },
    { label: "Nonstick", code: "GM03FBMCNC" },
    { label: "Nubuck", code: "GM03FBMCND" },
    { label: "Onyx", code: "GM03FBMCOA" },
    { label: "Opal", code: "GM03FBMCOB" },
    { label: "Organza", code: "GM03FBMCOC" },
    { label: "Ostrich", code: "GM03FBMCOD" },
    { label: "Ostrich Embossed", code: "GM03FBMCOE" },
    { label: "Oxford", code: "GM03FBMCOF" },
    { label: "Palladium", code: "GM03FBMCPA" },
    { label: "Paper Braid", code: "GM03FBMCPB" },
    { label: "Patent Leather", code: "GM03FBMCPC" },
    { label: "Pearl", code: "GM03FBMCPD" },
    { label: "Percale", code: "GM03FBMCPE" },
    { label: "Pinpoint", code: "GM03FBMCPF" },
    { label: "Pique", code: "GM03FBMCPG" },
    { label: "Plastic", code: "GM03FBMCPH" },
    { label: "Plastic/Acetate", code: "GM03FBMCPI" },
    { label: "Plastic/Metal", code: "GM03FBMCPJ" },
    { label: "Plush", code: "GM03FBMCPK" },
    { label: "Pointelle", code: "GM03FBMCPL" },
    { label: "Polycarbonate", code: "GM03FBMCPM" },
    { label: "Ponte", code: "GM03FBMCPN" },
    { label: "Poplin", code: "GM03FBMCPO" },
    { label: "Porcelain", code: "GM03FBMCPP" },
    { label: "Portuguese Flannel", code: "GM03FBMCPQ" },
    { label: "Propionate", code: "GM03FBMCPR" },
    { label: "PU", code: "GM03FBMCPS" },
    { label: "Quartz", code: "GM03FBMCQA" },
    { label: "Rattan", code: "GM03FBMCRA" },
    { label: "Resin", code: "GM03FBMCRB" },
    { label: "Rhodium", code: "GM03FBMCRC" },
    { label: "Ribbon", code: "GM03FBMCRD" },
    { label: "Rope", code: "GM03FBMRE" },
    { label: "Saffiano", code: "GM03FBMCSA" },
    { label: "Sateen", code: "GM03FBMCSB" },
    { label: "Satin", code: "GM03FBMCSC" },
    { label: "Scuba", code: "GM03FBMCSD" },
    { label: "Seagrass", code: "GM03FBMCSE" },
    { label: "Seersucker", code: "GM03FBMCSF" },
    { label: "Sequin", code: "GM03FBMCSG" },
    { label: "Shantung", code: "GM03FBMCSH" },
    { label: "Shearling", code: "GM03FBMCSI" },
    { label: "Sheeting", code: "GM03FBMCSJ" },
    { label: "Shell", code: "GM03FBMCSK" },
    { label: "Silicone", code: "GM03FBMCSL" },
    { label: "Sinamay", code: "GM03FBMCSM" },
    { label: "Slate", code: "GM03FBMCSN" },
    { label: "Slub", code: "GM03FBMCSO" },
    { label: "Snake Embossed", code: "GM03FBMCSP" },
    { label: "Snit", code: "GM03FBMCSQ" },
    { label: "Stainless Steel", code: "GM03FBMCSR" },
    { label: "Steel", code: "GM03FBMCST" },
    { label: "Sterling Silver", code: "GM03FBMCSU" },
    { label: "Stone", code: "GM03FBMCSV" },
    { label: "Stoneware", code: "GM03FBMCSW" },
    { label: "Straw", code: "GM03FBMCSX" },
    { label: "Styrofoam", code: "GM03FBMCSY" },
    { label: "Suede", code: "GM03FBMCSZ" },
    { label: "Sweater Yarn", code: "GM03FBMCSS" },
    { label: "Swiss Dot", code: "GM03FBMCWI" },
    { label: "Synthetic", code: "GM03FBMCYT" },
    { label: "Taffeta", code: "GM03FBMCTA" },
    { label: "Terra Cotta", code: "GM03FBMCTB" },
    { label: "Terry Cloth", code: "GM03FBMCTC" },
    { label: "Thermal", code: "GM03FBMCTD" },
    { label: "Titanium", code: "GM03FBMCTE" },
    { label: "Topaz", code: "GM03FBMCTF" },
    { label: "Tri-Ply Stainless Steel", code: "GM03FBMCTH" },
    { label: "Tricot", code: "GM03FBMCTG" },
    { label: "Tritan", code: "GM03FBMCTI" },
    { label: "Tulle", code: "GM03FBMCT" },
    { label: "Turquoise", code: "GM03FBMCTK" },
    { label: "Tweed", code: "GM03FBMCTL" },
    { label: "Tweed/Boucle", code: "GM03FBMCTM" },
    { label: "Twill", code: "GM03FBMCTN" },
    { label: "Velour", code: "GM03FBMCVA" },
    { label: "Velvet", code: "GM03FBMCVB" },
    { label: "Velveteen", code: "GM03FBMCVC" },
    { label: "Voile", code: "GM03FBMCVD" },
    { label: "Waffle", code: "GM03FBMCWA" },
    { label: "Wax", code: "GM03FBMCWB" },
    { label: "Wicker", code: "GM03FBMCWC" },
    { label: "Wire", code: "GM03FBMCWD" },
    { label: "Wood", code: "GM03FBMCWE" },
    { label: "Wood Alternative", code: "GM03FBMCWF" },
    { label: "Wool", code: "GM03FBMCWG" },
    { label: "Woven (generic)", code: "GM03FBMCWH" },
    { label: "Other", code: "GM03FBMC99" },
  ],
  "Fiber": [
    { label: "Acetate", code: "GM03FIBRAA" },
    { label: "Acrylic", code: "GM03FIBRAB" },
    { label: "Alpaca", code: "GM03FIBRAC" },
    { label: "Angora", code: "GM03FIBRAD" },
    { label: "Bamboo", code: "GM03FIBRBA" },
    { label: "Buffalo", code: "GM03FIBRBB" },
    { label: "Cashmere", code: "GM03FIBRCA" },
    { label: "Cotton", code: "GM03FIBRCB" },
    { label: "Cotton Blend", code: "GM03FIBRCC" },
    { label: "Cotton/Cashmere", code: "GM03FIBRCD" },
    { label: "Cotton/Elastane", code: "GM03FIBRCE" },
    { label: "Cotton/Lyocell", code: "GM03FIBRCF" },
    { label: "Cotton/Polyester", code: "GM03FIBRCG" },
    { label: "Cotton/Polyester/Elastane", code: "GM03FIBRCH" },
    { label: "Cotton/Rayon", code: "GM03FIBRCI" },
    { label: "Cotton/Silk", code: "GM03FIBRCJ" },
    { label: "Cow", code: "GM03FIBRCK" },
    { label: "Deer", code: "GM03FIBRDA" },
    { label: "Egyptian Cotton", code: "GM03FIBREA" },
    { label: "Elastane", code: "GM03FIBREB" },
    { label: "Flax", code: "GM03FIBRFA" },
    { label: "Goat", code: "GM03FIBRGA" },
    { label: "Hair On Hide", code: "GM03FIBRHA" },
    { label: "Haircalf", code: "GM03FIBRHB" },
    { label: "Hemp", code: "GM03FIBRHC" },
    { label: "Horse Hair", code: "GM03FIBRHD" },
    { label: "Jute", code: "GM03FIBRJA" },
    { label: "Lamb", code: "GM03FIBRLA" },
    { label: "Lambs Wool/Nylon", code: "GM03FIBRLB" },
    { label: "Leather", code: "GM03FIBRLC" },
    { label: "Leather/Nylon", code: "GM03FIBRLD" },
    { label: "Linen", code: "GM03FIBRLE" },
    { label: "Linen/Cotton", code: "GM03FIBRLF" },
    { label: "Linen/Silk", code: "GM03FIBRLG" },
    { label: "Lurex", code: "GM03FIBRLH" },
    { label: "Lyocell", code: "GM03FIBRLI" },
    { label: "Metallic Yarm", code: "GM03FIBRMA" },
    { label: "Microcotton", code: "GM03FIBRMB" },
    { label: "Microfiber", code: "GM03FIBRMC" },
    { label: "Modal", code: "GM03FIBRMD" },
    { label: "Modal/Elastane", code: "GM03FIBRME" },
    { label: "Mohair", code: "GM03FIBRMF" },
    { label: "Neoprene", code: "GM03FIBRNA" },
    { label: "Nylon", code: "GM03FIBRNB" },
    { label: "Nylon/Elastane", code: "GM03FIBRNC" },
    { label: "Olefin", code: "GM03FIBROA" },
    { label: "Paper", code: "GM03FIBRPA" },
    { label: "Pashmina", code: "GM03FIBRPB" },
    { label: "Pigskin", code: "GM03FIBRPC" },
    { label: "Pima Cotton", code: "GM03FIBRPD" },
    { label: "Pima Cotton Blend", code: "GM03FIBRPE" },
    { label: "Polyester", code: "GM03FIBRPF" },
    { label: "Polyester Blend", code: "GM03FIBRPG" },
    { label: "Polyester/Cotton", code: "GM03FIBRPH" },
    { label: "Polyester/Elastane", code: "GM03FIBRPI" },
    { label: "Polyester/Modal", code: "GM03FIBRPJ" },
    { label: "Polyester/Nylon", code: "GM03FIBRPK" },
    { label: "Polyester/Rayon", code: "GM03FIBRPL" },
    { label: "Polypropylene", code: "GM03FIBRPM" },
    { label: "Polyurethane", code: "GM03FIBRPN" },
    { label: "PVC", code: "GM03FIBRPO" },
    { label: "Qmiich", code: "GM03FIBRQM" },
    { label: "Raffia", code: "GM03FIBRRA" },
    { label: "Ramie", code: "GM03FIBRRB" },
    { label: "Rayon", code: "GM03FIBRRC" },
    { label: "Rayon (Viscose)", code: "GM03FIBRRD" },
    { label: "Rayon/Elastane", code: "GM03FIBRRE" },
    { label: "Rayon/Nylon", code: "GM03FIBRRF" },
    { label: "Rayon/Nylon/Elastane", code: "GM03FIBRRG" },
    { label: "Rhino", code: "GM03FIBRRH" },
    { label: "Rubber", code: "GM03FIBRRI" },
    { label: "Sheepskin", code: "GM03FIBRSA" },
    { label: "Silk", code: "GM03FIBRSB" },
    { label: "Sisal", code: "GM03FIBRSC" },
    { label: "Snake", code: "GM03FIBRSD" },
    { label: "Supplex", code: "GM03FIBRSE" },
    { label: "Supplex/Elastane", code: "GM03FIBRSF" },
    { label: "Turkish Cotton", code: "GM03FIBRTA" },
    { label: "UGG Wool", code: "GM03FIBRUA" },
    { label: "Vinyl", code: "GM03FIBRVA" },
    { label: "Viscose", code: "GM03FIBRVB" },
    { label: "Wool", code: "GM03FIBRWA" },
    { label: "Wool Blend", code: "GM03FIBRWB" },
    { label: "Wool/Bamboo", code: "GM03FIBRWC" },
    { label: "Wool/Cashmere", code: "GM03FIBRWD" },
    { label: "Wool/Elastane", code: "GM03FIBRWE" },
    { label: "Wool/Nylon/Cashmere", code: "GM03FIBRWF" },
    { label: "Wool/Silk", code: "GM03FIBRWG" },
    { label: "Other", code: "GM03FIBR99" },
  ],
  "Fit": [
    { label: "Relaxed", code: "GM03FITTRE" },
    { label: "Structured", code: "GM03FITTST" },
    { label: "Other", code: "GM04FITT99" },
  ],
  "Gender": [
    { label: "Female", code: "ZZ03GENDFE" },
    { label: "Gender Neutral", code: "ZZ03GENDUN" },
    { label: "Male", code: "ZZ03GENDMA" },
  ],
  "Heel Height Range": [
    { label: "Extra-High > 3 inch", code: "GM03HLHTEH" },
    { label: "Flat - 0 - .5 inch", code: "GM03HLHTFL" },
    { label: "High > 2 inch 3 inch", code: "GM03HLHTHI" },
    { label: "Low > .5 to 1 inch", code: "GM03HLHTLW" },
    { label: "Medium - > 1 inch - 2 inch", code: "GM03HLHTMD" },
    { label: "Other", code: "GM04HLHT99" },
  ],
  "Heel Material": [
    { label: "Cork", code: "GM03HLMTCK" },
    { label: "Leather", code: "GM03HLMTLE" },
    { label: "Metallic", code: "GM03HLMTME" },
    { label: "Rope", code: "GM03HLMTRP" },
    { label: "Synthetic", code: "GM03HLMTSY" },
    { label: "Textile/Fabric", code: "GM03HLMTTE" },
    { label: "Wood", code: "GM03HLMTWD" },
    { label: "Other", code: "GM04HLMT99" },
  ],
  "Heel Type": [
    { label: "Block", code: "GM03HLTYBL" },
    { label: "Comma", code: "GM03HLTYCM" },
    { label: "Cone", code: "GM03HLTYCN" },
    { label: "Demi-Wedge", code: "GM03HLTYDW" },
    { label: "Flare", code: "GM03HLTYFL" },
    { label: "Flatform", code: "GM03HLTYFF" },
    { label: "Kitten", code: "GM03HLTYKI" },
    { label: "Louis", code: "GM03HLTYLU" },
    { label: "No Heel/Flat", code: "GM03HLTYNH" },
    { label: "Novelty", code: "GM03HLTYNV" },
    { label: "Spool", code: "GM03HLTYSP" },
    { label: "Stacked", code: "GM03HLTYSA" },
    { label: "Stiletto/Pointed", code: "GM03HLTYSL" },
    { label: "Wedge", code: "GM03HLTYWE" },
    { label: "Other", code: "GM04HLTY99" },
  ],
  "Jewelry Type": [
    { label: "Costume", code: "JW03JWLTCS" },
    { label: "Fashion", code: "JW03JWLTFA" },
    { label: "Fine", code: "JW03JWLTFI" },
    { label: "Other", code: "JW04JWLT99" },
  ],
  "Knit Type": [
    { label: "Pom", code: "GM03KNITPM" },
    { label: "Skully", code: "GM03KNITTA" },
    { label: "Tassel", code: "GM03KNITSK" },
    { label: "Other", code: "GM04KNIT99" },
  ],
  "Leg Type": [
    { label: "Boot Cut", code: "GM03LGTYBC" },
    { label: "Flare Leg", code: "GM03LGTYFL" },
    { label: "Skinny Leg", code: "GM03LGTYSK" },
    { label: "Straight Leg", code: "GM03LGTYST" },
    { label: "Tapered", code: "GM03LGTYTA" },
    { label: "Wide Leg", code: "GM03LGTYWI" },
    { label: "Other", code: "GM04LGTY99" },
  ],
  "Length Description": [
    { label: "Above Knee", code: "GM03LNTHAK" },
    { label: "Ankle", code: "GM03LNTHAN" },
    { label: "Basketball", code: "GM03LNTHBA" },
    { label: "Below Knee", code: "GM03LNTHBK" },
    { label: "Capri/Calf", code: "GM03LNTHCC" },
    { label: "Car", code: "GM03LNTHCA" },
    { label: "Cropped", code: "GM03LNTHCR" },
    { label: "Extra Long", code: "GM03LNTHEL" },
    { label: "High-Low", code: "GM03LNTHHL" },
    { label: "Knee", code: "GM03LNTHHKN" },
    { label: "Long", code: "GM03LNTHLN" },
    { label: "Maxi", code: "GM03LNTHMX" },
    { label: "Mid", code: "GM03LNTHMD" },
    { label: "Midi Short", code: "GM03LNTHMS" },
    { label: "Mini", code: "GM03LNTHMN" },
    { label: "Regular/Full", code: "GM03LNTHRF" },
    { label: "Short", code: "GM03LNTHST" },
    { label: "Skimmer", code: "GM03LNTHSK" },
    { label: "Tall", code: "GM03LNTHTA" },
    { label: "Tea/Ballet", code: "GM03LNTHTB" },
    { label: "Tunic", code: "GM03LNTHTU" },
    { label: "Waist", code: "GM03LNTHWA" },
    { label: "Walker", code: "GM03LNTHWK" },
    { label: "Waltz", code: "GM03LNTHWZ" },
    { label: "Other", code: "GM04LNTH99" },
  ],
  "Lining Material": [
    { label: "Antimicrobial", code: "GM03LIMTAN" },
    { label: "Cotton", code: "GM03LIMTCT" },
    { label: "Fabric", code: "GM03LIMTFD" },
    { label: "Faux Fur", code: "GM03LIMTFB" },
    { label: "Faux Leather", code: "GM03LIMTFL" },
    { label: "Faux Shearling", code: "GM03LIMTFS" },
    { label: "Fleece", code: "GM03LIMTFC" },
    { label: "Gel", code: "GM03LIMTGE" },
    { label: "Leather", code: "GM03LIMTLE" },
    { label: "Logo Lining", code: "GM03LIMTLL" },
    { label: "Memory Foam", code: "GM03LIMTMF" },
    { label: "Mesh", code: "GM03LIMTME" },
    { label: "Nylon", code: "GM03LIMTNY" },
    { label: "Organic Material", code: "GM03LIMTOM" },
    { label: "Polyester", code: "GM03LIMTPR" },
    { label: "PU", code: "GM03LIMTPU" },
    { label: "PVC", code: "GM03LIMTPV" },
    { label: "Quilted", code: "GM03LIMTQT" },
    { label: "Shearling Lined", code: "GM03LIMTSL" },
    { label: "Sherpa", code: "GM03LIMTSP" },
    { label: "Straw", code: "GM03LIMTST" },
    { label: "Synthetic", code: "GM03LIMTSY" },
    { label: "Taffeta", code: "GM03LIMTTA" },
    { label: "Other", code: "GM04LIMT99" },
  ],
  "Metal": [
    { label: "Aluminum", code: "JW03METLAI" },
    { label: "Brass", code: "JW03METLBR" },
    { label: "Bronze", code: "JW03METLBZ" },
    { label: "Cast Iron", code: "JW03METLCI" },
    { label: "Copper", code: "JW03METLCU" },
    { label: "Gold", code: "JW03METLAU" },
    { label: "Gold Plated", code: "JW03METLGP" },
    { label: "Nickel", code: "JW03METLNI" },
    { label: "Palladium", code: "JW03METLPD" },
    { label: "Platinum", code: "JW03METLPT" },
    { label: "Rhodium", code: "JW03METLRH" },
    { label: "Rose Gold", code: "JW03METLRG" },
    { label: "Silver", code: "JW03METLAG" },
    { label: "Stainless Steel", code: "JW03METLSS" },
    { label: "Titanium", code: "JW03METLTI" },
    { label: "White Gold", code: "JW03METLWG" },
    { label: "Other", code: "JW04METL99" },
  ],
  "Metal Composition": [
    { label: "18/0", code: "GM03MTLCCA" },
    { label: "18/10", code: "GM03MTLCCB" },
    { label: "18/8", code: "GM03MTLCCC" },
    { label: "Other", code: "GM04MTLC99" },
  ],
  "Necklace Type": [
    { label: "Chain", code: "JW03NKLCCA" },
    { label: "Choker", code: "JW03NKLCCH" },
    { label: "Collar", code: "JW03NKLCCL" },
    { label: "Locket", code: "JW03NKLCLK" },
    { label: "Multi Strand", code: "JW03NKLCMS" },
    { label: "Pearl Strand", code: "JW03NKLCPS" },
    { label: "Pendant", code: "JW03NKLCPE" },
    { label: "Y-Necklace", code: "JW03NKLCYN" },
    { label: "Other", code: "JW04NKLC99" },
  ],
  "Number of Settings": [
    { label: "Eight", code: "GM03SETSEI" },
    { label: "Four", code: "GM03SETSFR" },
    { label: "Six", code: "GM03SETSSX" },
    { label: "Twelve", code: "GM03SETSTW" },
    { label: "Other", code: "GM04SETS99" },
  ],
  "Occasion": [
    { label: "Active/Workout", code: "GM030CCNAW" },
    { label: "Anniversary", code: "GM030CCNAN" },
    { label: "Athleisure", code: "GM030CCNAL" },
    { label: "Athletic", code: "GM030CCNAT" },
    { label: "Baby Shower", code: "GM030CCNBS" },
    { label: "Beach/Pool", code: "GM030CCNBP" },
    { label: "Birthday", code: "GM030CCNBI" },
    { label: "Bride", code: "GM030CCNBR" },
    { label: "Bridesmaid", code: "GM030CCNBD" },
    { label: "Career", code: "GM030CCNCR" },
    { label: "Casual", code: "GM030CCNCS" },
    { label: "Christening/Baptism", code: "GM030CCNCB" },
    { label: "Cocktail", code: "GM030CCNCT" },
    { label: "Comfort", code: "GM030CCNCF" },
    { label: "Communion", code: "GM030CCNCM" },
    { label: "Daytime", code: "GM030CCNDT" },
    { label: "Dress", code: "GM030CCNDR" },
    { label: "Easter", code: "GM030CCNEA" },
    { label: "Engagement", code: "GM030CCNEN" },
    { label: "Evening", code: "GM030CCNEV" },
    { label: "Fashion", code: "GM030CCNFA" },
    { label: "Flower Girl", code: "GM030CCNFG" },
    { label: "Formal", code: "GM030CCNFR" },
    { label: "Graduation", code: "GM030CCNGG" },
    { label: "Groom", code: "GM030CCNGM" },
    { label: "Homecoming", code: "GM030CCNHM" },
    { label: "Lounge", code: "GM030CCNLN" },
    { label: "Mother of the Bride", code: "GM030CCNMB" },
    { label: "Outdoor", code: "GM030CCNUT" },
    { label: "Performance", code: "GM030CCNPE" },
    { label: "Prom", code: "GM030CCNPR" },
    { label: "Resort", code: "GM030CCNRE" },
    { label: "Ring Bearer", code: "GM030CCNRB" },
    { label: "Safety", code: "GM030CCNSA" },
    { label: "Wedding", code: "GM030CCNSU" },
    { label: "Work/Uniform", code: "GM030CCNWU" },
    { label: "Other", code: "GM040CCN99" },
  ],
  "Open/Closed Toe": [
    { label: "Closed", code: "GM03OPCLCL" },
    { label: "Open", code: "GM03OPCLOP" },
  ],
  "Outsole Type": [
    { label: "Dimpled", code: "GM030UTSDP" },
    { label: "Driver", code: "GM030UTSDR" },
    { label: "Embossed", code: "GM03OUTSEM" },
    { label: "Heavy Lug", code: "GM03OUTSHV" },
    { label: "Light Lug", code: "GM030UTSLL" },
    { label: "Non-Slip", code: "GM030UTSNS" },
    { label: "Tooth", code: "GM030UTSTT" },
    { label: "Tread", code: "GM030UTSTR" },
    { label: "Other", code: "GM040UTS99" },
  ],
  "Ring Type": [
    { label: "Band", code: "JW03RINGBA" },
    { label: "Midi", code: "JW03RINGMI" },
    { label: "Signet", code: "JW03RINGSI" },
    { label: "Stacked", code: "JW03RINGST" },
    { label: "Toe", code: "JW03RINGTE" },
    { label: "Other", code: "JW04RING99" },
  ],
  "Shoe Style": [
    { label: "Alpine Boot", code: "GM03SHOEAB" },
    { label: "Ankle Strap", code: "GM03SHOEAS" },
    { label: "Athleisure", code: "GM03SHOEAT" },
    { label: "Ballet", code: "GM03SHOEBA" },
    { label: "Biker Boot", code: "GM03SHOEBI" },
    { label: "Boat Shoe", code: "GM03SHOEBS" },
    { label: "Bootie", code: "GM03SHOEBT" },
    { label: "Caged", code: "GM03SHOECA" },
    { label: "Chelsea", code: "GM03SHOECH" },
    { label: "Chukka", code: "GM03SHOECK" },
    { label: "Cleats", code: "GM03SHOECL" },
    { label: "Combat Boot", code: "GM03SHOECB" },
    { label: "Comfort", code: "GM03SHOECF" },
    { label: "Cowboy", code: "GM03SHOECW" },
    { label: "D'Orsay", code: "GM03SHOEDR" },
    { label: "Derby", code: "GM03SHOEDE" },
    { label: "Driver", code: "GM03SHOEDV" },
    { label: "Espadrille", code: "GM03SHOEES" },
    { label: "Fisherman", code: "GM03SHOEFI" },
    { label: "Flip-Flop", code: "GM03SHOEFP" },
    { label: "Ghillie", code: "GM03SHOEGH" },
    { label: "Gladiator", code: "GM03SHOEGL" },
    { label: "High Top", code: "GM03SHOEHT" },
    { label: "Huarache", code: "GM03SHOEHU" },
    { label: "Instep Strap", code: "GM03SHOEIS" },
    { label: "Jellies", code: "GM03SHOEJE" },
    { label: "Low Top", code: "GM03SHOELT" },
    { label: "Mary Jane", code: "GM03SHOEMJ" },
    { label: "Military & Police", code: "GM03SHOEMP" },
    { label: "Moccasin", code: "GM03SHOEMC" },
    { label: "Monk Strap", code: "GM03SHOEMS" },
    { label: "Penny Loafer", code: "GM03SHOEPE" },
    { label: "Rain Boot", code: "GM03SHOERA" },
    { label: "Riding Boot", code: "GM03SHOERI" },
    { label: "Shootie", code: "GM03SHOESH" },
    { label: "Slide", code: "GM03SHOESL" },
    { label: "Sling Back", code: "GM03SHOESB" },
    { label: "Slip On", code: "GM03SHOESO" },
    { label: "Smoking Slipper", code: "GM03SHOESM" },
    { label: "Snow Boot", code: "GM03SHOESW" },
    { label: "Sport Specific", code: "GM03SHOESS" },
    { label: "Strappy", code: "GM03SHOESY" },
    { label: "T-Strap", code: "GM03SHOETS" },
    { label: "Thong", code: "GM03SHOETH" },
    { label: "Water Shoe", code: "GM03SHOEWS" },
    { label: "Wingtip", code: "GM03SHOEWT" },
    { label: "Work Boot", code: "GM03SHOEWB" },
    { label: "Other", code: "GM04SHOE99" },
  ],
  "Shoe Type": [
    { label: "Boots/Booties", code: "GM03SETPBB" },
    { label: "Clogs/Mules", code: "GM03SETPCM" },
    { label: "Flats", code: "GM03SETPFL" },
    { label: "Loafers", code: "GM03SETPLM" },
    { label: "Oxfords", code: "GM03SETPXF" },
    { label: "Pumps", code: "GM03SETPPP" },
    { label: "Sandals", code: "GM03SETPSA" },
    { label: "Slippers", code: "GM03SETPSL" },
    { label: "Sneakers", code: "GM03SETPSN" },
    { label: "Other", code: "GM04SETP99" },
  ],
  "Sleepwear Type": [
    { label: "Bridal", code: "GM03SLPTBR" },
    { label: "Caftan", code: "GM03SLPTCA" },
    { label: "Chemise", code: "GM03SLPTCH" },
    { label: "Gown", code: "GM03SLPTGW" },
    { label: "Loungewear", code: "GM03SLPTLN" },
    { label: "Maternity", code: "GM03SLPTMA" },
    { label: "One Piece", code: "GM03SLPTOP" },
    { label: "PJ Set", code: "GM03SLPTPJ" },
    { label: "Robe", code: "GM03SLPTRO" },
    { label: "Sleep Pant", code: "GM03SLPTSP" },
    { label: "Sleep Shirt", code: "GM03SLPTSH" },
    { label: "Sleep Short", code: "GM03SLPTSO" },
    { label: "Sleep Top", code: "GM03SLPTST" },
    { label: "Other", code: "GM03SLPT99" },
  ],
  "Sleeve Type": [
    { label: "1/2 Sleeve", code: "GM03SLVTHT" },
    { label: "1/4 sleeve", code: "GM03SLVTQS" },
    { label: "3/4 Sleeve", code: "GM03SLVTTT" },
    { label: "Cap", code: "GM03SLVTCS" },
    { label: "Elbow", code: "GM03SLVTES" },
    { label: "Long", code: "GM03SLVTLO" },
    { label: "Roll-Tab (3/4 to short)", code: "GM03SLVTTR" },
    { label: "Roll-Tab (Long to elbow/short)", code: "GM03SLVTRT" },
    { label: "Short", code: "GM03SLVTST" },
    { label: "Sleeveless", code: "GM03SLVTS4" },
    { label: "Spaghetti Strap", code: "GM03SLVTSI" },
    { label: "Other Sleeve Type*", code: "GM04SLVT99" },
  ],
  "Sole Type": [
    { label: "Leather", code: "GM03SOLTLS" },
    { label: "Natural Fiber", code: "GM03SOLTNS" },
    { label: "Recycled", code: "GM03SOLTRE" },
    { label: "Rubber", code: "GM03SOLTRS" },
    { label: "Synthetic", code: "GM03SOLTSJ" },
    { label: "Other Sole Type", code: "GM04SOLT99" },
  ],
  "Special Embellishment": [
    { label: "Beads", code: "GM03SPEMBE" },
    { label: "Belting", code: "GM03SPEMBL" },
    { label: "Bows", code: "GM03SPEMBW" },
    { label: "Braiding", code: "GM03SPEMBR" },
    { label: "Broguing", code: "GM03SPEMBG" },
    { label: "Buckle(s)", code: "GM03SPEMBU" },
    { label: "Chain", code: "GM03SPEMCH" },
    { label: "Contrast Stitching", code: "GM03SPEMCS" },
    { label: "Crochet", code: "GM03SPEMCR" },
    { label: "Cuff", code: "GM03SPEMCF" },
    { label: "Cut-outs", code: "GM03SPEMCU" },
    { label: "Embroidery", code: "GM03SPEMEM" },
    { label: "Feathers", code: "GM03SPEMFE" },
    { label: "Filigree", code: "GM03SPEMFI" },
    { label: "Flower", code: "GM03SPEMFL" },
    { label: "Fringe", code: "GM03SPEMFR" },
    { label: "Glitter", code: "GM03SPEMGL" },
    { label: "Grommets", code: "GM03SPEMGR" },
    { label: "Harness", code: "GM03SPEMHA" },
    { label: "Jewels", code: "GM03SPEMJE" },
    { label: "Knotting", code: "GM03SPEMKN" },
    { label: "Lace", code: "GM03SPEMLA" },
    { label: "Logo", code: "GM03SPEMLG" },
    { label: "Metal", code: "GM03SPEMME" },
    { label: "Metal Ornament", code: "GM03SPEMMR" },
    { label: "Nailheads", code: "GM03SPEMNA" },
    { label: "Penny Keeper", code: "GM03SPEMPK" },
    { label: "Perforation", code: "GM03SPEMPE" },
    { label: "Piping", code: "GM03SPEMPI" },
    { label: "Pleated", code: "GM03SPEMPL" },
    { label: "Quilting", code: "GM03SPEMQU" },
    { label: "Rhinestones", code: "GM03SPEMRH" },
    { label: "Ruffles", code: "GM03SPEMRU" },
    { label: "Sequins", code: "GM03SPEMSE" },
    { label: "Speed Lacing", code: "GM03SPEMSL" },
    { label: "Stones", code: "GM03SPEMSN" },
    { label: "Studded", code: "GM03SPEMST" },
    { label: "Tassels", code: "GM03SPEMTA" },
    { label: "Tortoise", code: "GM03SPEMTS" },
    { label: "Wood", code: "GM03SPEMWD" },
    { label: "Zipper", code: "GM03SPEMZI" },
    { label: "Other", code: "GM04SPEM99" },
  ],
  "Sport": [
    { label: "Badminton", code: "ZZ03SPRTBD" },
    { label: "Baseball", code: "ZZ03SPRTBA" },
    { label: "Basketball", code: "ZZ03SPRTBK" },
    { label: "Bocce Ball", code: "ZZ03SPRTBB" },
    { label: "Bowling", code: "ZZ03SPRTBW" },
    { label: "Boxing/Martial Arts", code: "ZZ03SPRTBM" },
    { label: "Climbing", code: "ZZ03SPRTCL" },
    { label: "Cross Country", code: "ZZ03SPRTCC" },
    { label: "Cross-Training", code: "ZZ03SPRTCT" },
    { label: "Cycling", code: "ZZ03SPRTCY" },
    { label: "Dance", code: "ZZ03SPRTDA" },
    { label: "Football", code: "ZZ03SPRTFT" },
    { label: "Golf", code: "ZZ03SPRTGF" },
    { label: "Hiking", code: "ZZ03SPRTHI" },
    { label: "Hockey", code: "ZZ03SPRTHK" },
    { label: "Hunting", code: "ZZ03SPRTHU" },
    { label: "Lacrosse", code: "ZZ03SPRTLA" },
    { label: "Racing", code: "ZZ03SPRTRA" },
    { label: "Racquetball", code: "ZZ03SPRTRC" },
    { label: "Rowing", code: "ZZ03SPRTRW" },
    { label: "Running", code: "ZZ03SPRTRU" },
    { label: "Skiing", code: "ZZ03SPRTSK" },
    { label: "Soccer", code: "ZZ03SPRTSC" },
    { label: "Softball", code: "ZZ03SPRTSF" },
    { label: "Tennis", code: "ZZ03SPRTTE" },
    { label: "Walking", code: "ZZ03SPRTWK" },
    { label: "Water Skiing", code: "ZZ03SPRTWA" },
    { label: "Wrestling", code: "ZZ03SPRTWR" },
    { label: "Yoga", code: "ZZ03SPRTYG" },
    { label: "Other", code: "ZZ04SPRT99" },
  ],
  "Toe Shape": [
    { label: "Almond", code: "GM03TOESAL" },
    { label: "Chisel", code: "GM03TOESCH" },
    { label: "Oblique", code: "GM03TOESOB" },
    { label: "Pointy", code: "GM03TOESPY" },
    { label: "Round", code: "GM03TOESRD" },
    { label: "Snip", code: "GM03TOESSN" },
    { label: "Square", code: "GM03TOESSQ" },
    { label: "Other", code: "GM04TOES99" },
  ],
  "Toe Style": [
    { label: "Apron Toe", code: "GM03TOESAP" },
    { label: "Bike Toe", code: "GM03TOESBI" },
    { label: "Cap Toe", code: "GM03TOESCT" },
    { label: "Peep Toe", code: "GM03TOESPT" },
    { label: "Split Toe", code: "GM03TOESSP" },
    { label: "Steel Toe", code: "GM03TOESST" },
    { label: "Tabi Toe", code: "GM03TOESTA" },
    { label: "Other", code: "GM04TOES99" },
  ],
  "Waistband Type": [
    { label: "", code: "GM03WBTPNN" },
    { label: "Band Roll", code: "GM03WBTPBR" },
    { label: "Belt Hook", code: "GM03WBTPBH" },
    { label: "D-ring", code: "GM03WBTPDR" },
    { label: "Drawstring", code: "GM03WBTPDS" },
    { label: "Expander", code: "GM03WBTPEX" },
    { label: "Full Elastic", code: "GM03WBTPFE" },
    { label: "Half Elastic", code: "GM03WBTPHE" },
    { label: "Hook and Loop", code: "GM03WBTPVE" },
    { label: "Ino-Flex", code: "GM03WBTPIF" },
    { label: "Inside Adjustable", code: "GM03WBTPIA" },
    { label: "Knit", code: "GM03WBTPKN" },
    { label: "Maternity", code: "GM03WBTPMT" },
    { label: "Rigid", code: "GM03WBTPRG" },
    { label: "Self-Fabric Underwear", code: "GM03WBTPSF" },
    { label: "Side Elastic", code: "GM03WBTPSE" },
    { label: "Side Tab", code: "GM03WBTPST" },
    { label: "Stretch Elastic", code: "GM03WBTPSR" },
    { label: "Other", code: "GM04WBTP99" },
  ],
  "Watch Case Shape": [
    { label: "Oval", code: "JW03WACSVA" },
    { label: "Rectangular", code: "JW03WACSRE" },
    { label: "Round", code: "JW03WACSRN" },
    { label: "Square", code: "JW03WACSSQ" },
    { label: "Other", code: "JW04WACS99" },
  ],
  "Water Repellent": [
    { label: "Water Resistant", code: "ZZ03WATRRE" },
    { label: "Waterproof", code: "ZZ03WATRPF" },
    { label: "Other", code: "ZZ04WATR99" },
  ],
}

/** Values for an attribute, or an empty array when it is free-text. */
export function getCodeListValues(codeListName: string | undefined): Gs1Value[] {
  return codeListName ? (GS1_CODE_LISTS[codeListName] ?? []) : []
}
